facebook: &facebook
  fb_app_id: 361505903895246 

elasticsearch: &elasticsearch
  elasticsearch_api_url: http://seattleblend.com:9200/

twitter:
  consumer_key: KTUsgbQa6JvXHzsdAoBfw
  consumer_secret: vSD2zY4mo0guod2noUaU9FUXDdO9JfsDNsUyFlB3J4Y
  oauth_token: 122466898-sXDCRKIY3ciCzPA3cycfWoMpB6YuIPiX6wkKbLY
  oauth_token_secret: wo9W2MDYGogvGuIOsKOOGgvdrlZZwH8p03e0I6F4oo
  auth_method: :oauth

open_calais: &open_calais
  open_calais_api_key: du295ff4zrg3rd4bwdk86xhy

development:
  <<: *facebook
  <<: *open_calais
  <<: *elasticsearch
  elasticsearch_api_url: http://localhost:9200/
  elasticsearch_index: 'staging'
  host: http://localhost:3000/

test:
  <<: *facebook
  <<: *open_calais
  <<: *elasticsearch

staging:
  <<: *facebook
  <<: *open_calais
  <<: *elasticsearch
  elasticsearch_index: 'staging'
  host: http://seattleblend.com

production:
  <<: *facebook
  <<: *open_calais
  <<: *elasticsearch
