CountFacebookLikes:
  cron: "0 */1 * * *"
  class: FacebookCounter
  description: "Updates the facebook likes count"

UpdateFeeds:
  cron: "45 */1 * * *"
  class: FeedUpdater
  description: "Update the feeds from the sources"
